name: run-tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit
