name: PhpUnit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=clover.xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
